#!/usr/bin/env python3
"""Build revision-ready tables from adapted-baseline and ablation outputs.

The script never invents rows: missing experiments are reported as pending and
their LaTeX inputs are omitted. This keeps the manuscript honest before cloud
experiments have been synchronized.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAPER_GENERATED = ROOT / "Paper" / "generated"


def read_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def fmt(value: float, digits: int = 2) -> str:
    return f"{value:.{digits}f}"


def summarize_dir(root: Path, task: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for protocol_dir in sorted(root.glob("*/")):
        data = read_rows(protocol_dir / "all_combinations.csv")
        if not data:
            continue
        if task == "HPE":
            mpjpe = [1000.0 * float(row["mpjpe"]) for row in data]
            pa = [1000.0 * float(row["pa_mpjpe"]) for row in data]
            full = next((row for row in data if row["modality_set"] in {"vk+depth+lidar+mmwave+wifi-csi", "vk+depth+lidar+mmwave"}), data[-1])
            rows.append({
                "protocol": protocol_dir.name,
                "count": str(len(data)),
                "mpjpe": fmt(sum(mpjpe) / len(mpjpe)),
                "pa_mpjpe": fmt(sum(pa) / len(pa)),
                "full_mpjpe": fmt(1000.0 * float(full["mpjpe"])),
                "full_pa_mpjpe": fmt(1000.0 * float(full["pa_mpjpe"])),
            })
        else:
            acc = [100.0 * float(row["acc"]) for row in data]
            f1 = [100.0 * float(row["macro_f1"]) for row in data]
            full = next((row for row in data if row["modality_set"] in {"vk+depth+lidar+mmwave", "vk+depth+lidar+mmwave+wifi-csi"}), data[-1])
            rows.append({
                "protocol": protocol_dir.name,
                "count": str(len(data)),
                "acc": fmt(sum(acc) / len(acc)),
                "f1": fmt(sum(f1) / len(f1)),
                "full_acc": fmt(100.0 * float(full["acc"])),
                "full_f1": fmt(100.0 * float(full["macro_f1"])),
            })
    return rows


def write_adapted_table() -> None:
    root = ROOT / "outputs" / "adapted_xfi_vk_baseline"
    hpe = summarize_dir(root / "HPE", "HPE")
    har = summarize_dir(root / "HAR", "HAR")
    lines = ["% Auto-generated by scripts/build_revision_materials.py.", "\\begin{table}[t]", "\\centering", "\\caption{Matched Adapted X-Fi-VK baseline.}", "\\label{tab:adapted_xfi_vk}"]
    if hpe or har:
        lines += ["\\begin{tabular}{lrrrr}", "\\toprule", "Task/protocol & Avg. primary & Avg. secondary & Full primary & Full secondary \\\\ ", "\\midrule"]
        for row in hpe:
            lines.append(f"HPE/{row['protocol']} & {row['mpjpe']} & {row['pa_mpjpe']} & {row['full_mpjpe']} & {row['full_pa_mpjpe']} \\\\ ")
        for row in har:
            lines.append(f"HAR/{row['protocol']} & {row['acc']} & {row['f1']} & {row['full_acc']} & {row['full_f1']} \\\\ ")
        lines += ["\\bottomrule", "\\end{tabular}"]
    else:
        lines += ["\\emph{Pending cloud run; no result is inserted.}"]
    lines += ["\\end{table}"]
    (PAPER_GENERATED / "adapted_xfi_vk_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_profile_table() -> None:
    root = ROOT / "outputs" / "sp_sfc_ablation"
    rows: list[tuple[str, str, str, str]] = []
    for task in ("HPE", "HAR"):
        for profile_dir in sorted((root / task).glob("*/")):
            data = read_rows(profile_dir / "all_combinations.csv")
            if not data:
                continue
            if task == "HPE":
                primary = sum(1000.0 * float(row["mpjpe"]) for row in data) / len(data)
                secondary = sum(1000.0 * float(row["pa_mpjpe"]) for row in data) / len(data)
            else:
                primary = sum(100.0 * float(row["acc"]) for row in data) / len(data)
                secondary = sum(100.0 * float(row["macro_f1"]) for row in data) / len(data)
            rows.append((task, profile_dir.name, fmt(primary), fmt(secondary)))
    lines = ["% Auto-generated by scripts/build_revision_materials.py.", "\\begin{table}[t]", "\\centering", "\\caption{SP-SFC loss-profile ablation over all modality subsets.}", "\\label{tab:sp_sfc}"]
    if rows:
        lines += ["\\begin{tabular}{llrr}", "\\toprule", "Task & Profile & Primary & Secondary \\\\ ", "\\midrule"]
        lines += [f"{task} & {profile} & {primary} & {secondary} \\\\ " for task, profile, primary, secondary in rows]
        lines += ["\\bottomrule", "\\end{tabular}"]
    else:
        lines += ["\\emph{Pending cloud run; no result is inserted.}"]
    lines += ["\\end{table}"]
    (PAPER_GENERATED / "sp_sfc_ablation_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_dual_table() -> None:
    source = ROOT / "dual_readout_ablation" / "dual_readout_ablation_summary.csv"
    rows = read_rows(source)
    lines = ["% Auto-generated by scripts/build_revision_materials.py.", "\\begin{center}", "\\small", "\\textbf{Task-dependent readout ablation.}\\par", "\\vspace{2pt}"]
    if rows:
        lines += ["\\begin{tabular}{llrr}", "\\toprule", "Task & Readout & Primary & Secondary \\\\ ", "\\midrule"]
        for row in rows:
            mode = row["mode"].replace("_", "-")
            lines.append(f"{row['task']} & {mode} & {float(row['all_subset_metric']):.2f} & {float(row['secondary_metric']):.2f} \\\\ ")
        lines += ["\\bottomrule", "\\end{tabular}"]
    else:
        lines += ["\\emph{No synchronized dual-readout summary found.}"]
    lines += ["\\end{center}"]
    (PAPER_GENERATED / "dual_readout_revision_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    PAPER_GENERATED.mkdir(parents=True, exist_ok=True)
    write_adapted_table()
    write_profile_table()
    write_dual_table()
    print(f"Revision materials written to {PAPER_GENERATED}")


if __name__ == "__main__":
    main()
